"""empty message

Revision ID: 40f878743ee
Revises: None
Create Date: 2015-04-18 13:25:12.662984

"""

# revision identifiers, used by Alembic.
revision = '40f878743ee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apps')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('start_file', sa.TEXT(), nullable=True),
    sa.Column('start_args', sa.TEXT(), nullable=True),
    sa.Column('stop_file', sa.TEXT(), nullable=True),
    sa.Column('stop_args', sa.TEXT(), nullable=True),
    sa.Column('compare_term', sa.TEXT(), nullable=True),
    sa.Column('check_name', sa.BOOLEAN(), nullable=True),
    sa.Column('check_exe', sa.BOOLEAN(), nullable=True),
    sa.Column('check_cmd', sa.BOOLEAN(), nullable=True),
    sa.Column('start_in_command_prompt', sa.BOOLEAN(), nullable=True),
    sa.Column('stop_in_command_prompt', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
